[2019-10-06 17:51:55,535] [run.py:49	] [ERROR] [GET /favicon.ico	] 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. 
[2019-10-06 17:51:55,540] [run.py:50	] [ERROR] [GET /favicon.ico	] Traceback (most recent call last):
  File "/Users/vego/.pyenv/versions/3.6.0/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vego/.pyenv/versions/3.6.0/lib/python3.6/site-packages/flask/app.py", line 1925, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/vego/.pyenv/versions/3.6.0/lib/python3.6/site-packages/flask/app.py", line 1907, in raise_routing_exception
    raise request.routing_exception
  File "/Users/vego/.pyenv/versions/3.6.0/lib/python3.6/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/Users/vego/.pyenv/versions/3.6.0/lib/python3.6/site-packages/werkzeug/routing.py", line 1799, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
 
